export const STORIES_FETCH_INIT = 'STORIES_FETCH_INIT';
export const STORIES_FETCH_SUCCESS = 'STORIES_FETCH_SUCCESS';
export const STORIES_FETCH_FAILURE = 'STORIES_FETCH_FAILURE';
export const REMOVE_STORY = 'REMOVE_STORY';